name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:

  freezed_annotation:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_native_splash: ^2.4.0
  freezed:
  build_runner:
  json_serializable:

  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0




flutter:
  fonts:
    - family: Alpen
      fonts:
        - asset: assets/fonts/AlpenFontFree.otf
  assets:
    - assets/images/


  uses-material-design: true

flutter_native_splash:
  color: "#70CDFF"
  image: assets/images/splash.png
  fullscreen: true
